name: Selenium BDD Test

# Allow the workflow to be triggered manually
on:
  workflow_dispatch:  # Enables manual triggering

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout the repository code

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Set up Maven
      uses: actions/setup-java@v3
      with:
        distribution: 'adopt'
        java-version: '11'
        cache: maven

    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y google-chrome-stable  # Install Chrome browser

    - name: Run tests with Maven
      run: mvn clean test  # Run Maven tests

    - name: Archive test reports
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-report
        path: target/surefire-reports/  # Uploads test report to GitHub Action logs
